barriers:
  kwargs:
    mean: 1.8
    min_cutoff: 0.0
    std: 0.5112898972268959
  type: gaussian
boundary_conditions:
  driving_component: xx
  mixed_targets:
    yy: 0.0
  mixed_tol: 1.0
detection:
  ignore_drop_steps: 10
  max_cascade_steps_pct: 0.3
  max_kmc_steps_pct: 0.3
  stop_on_stress_drop: 0.2
  stop_post_drop_steps: 20
  stress_drop_lookback: 10
dynamics:
  cascade_timing: none
  fast_patching:
    enabled: false
    patch_radius: 3
    sync_interval: 100
  instability_mode: kmc
  nu0: 1.0e13
  physical_strain_rate: 1000000000.0
  scale_rate_by_volume: false
  temperature: 300.0
loading:
  eps_target: 0.175
  step_size: 0.0001
material:
  E:
    mode: constant
    value: 68.0
  nu:
    mode: constant
    value: 0.36
output:
  checkpoint_interval: none
  directory: trial_322_sys1_s1/simulation_results
  duplicate_directory_action: delete
  enable_cascade_log: false
  enable_config_backup: false
  enable_console: false
  enable_global_log: false
  enable_kmc_log: false
  enable_plotting: false
  enable_save_q: false
  enable_summary_log: true
  save_q_elastic_only: true
  save_q_interval: 1
  summary_filename: summary_log.txt
  track_cascades: false
  vtk_elastic_only: true
  vtk_interval: none
physics:
  enable_softening: true
  jp: 35.8878383754188
  jt: 0
  neighbor_softening_fraction: 0.0
  q_act_temp: 0.37
  redraw_barriers: true
  redraw_directions: true
  softening_cap: 1.4587010693297975
  softening_scheme: isotropic
  stability_threshold: 0.0
seed: 1
simulation_type: kmc
system:
  M: 20
  dimensionality: 2d
  gamma0: 0.13006115299746487
  num_threads: 1
  nx: 128
  ny: 128
  pixel: 0.6904741834526273
  plane_mode: plane_stress
  strain_assumption: "finite_strain"